In [42]:
import cvxpy as cp
import numpy as np
from sklearn.cluster import SpectralClustering
f_count = [('er', 44109),
 ('in', 40899),
 ('ar', 29110),
 ('es', 28073),
 ('or', 27803),
 ('st', 27369),
 ('an', 27011),
 ('no', 24938),
 ('it', 24248),
 ('et', 22645),
 ('en', 21483),
 ('at', 20169),
 ('al', 19878),
 ('ot', 19731),
 ('de', 19526),
 ('is', 16403),
 ('gn', 15834),
 ('rt', 15534),
 ('co', 15422),
 ('ce', 15341),
 ('il', 15004),
 ('ht', 14856),
 ('fo', 14569),
 ('el', 12934),
 ('io', 12224),
 ('eh', 11725),
 ('as', 11518),
 ('lo', 11197),
 ('ad', 10994),
 ('nt', 10774),
 ('em', 10717),
 ('ir', 10713),
 ('am', 10639),
 ('mo', 10500),
 ('ac', 10182),
 ('ae', 9926),
 ('ev', 9903),
 ('ci', 9764),
 ('ah', 9511),
 ('ou', 9223),
 ('cn', 9209),
 ('op', 8735),
 ('di', 8523),
 ('ep', 8367),
 ('su', 8286),
 ('eg', 8205),
 ('ap', 7703),
 ('ai', 7588),
 ('dn', 7529),
 ('os', 7493),
 ('pr', 7233),
 ('ew', 7205),
 ('im', 7051),
 ('gr', 7039),
 ('ch', 6953),
 ('tu', 6716),
 ('gi', 6572),
 ('ck', 6160),
 ('ru', 6144),
 ('hs', 6127),
 ('ow', 5969),
 ('nu', 5778),
 ('hi', 5680),
 ('ek', 5669),
 ('pu', 5630),
 ('iv', 5622),
 ('ct', 5603),
 ('ns', 5600),
 ('lu', 5546),
 ('ho', 5436),
 ('ly', 5251),
 ('do', 5147),
 ('ag', 4898),
 ('fi', 4844),
 ('ei', 4744),
 ('ay', 4598),
 ('rs', 4525),
 ('cr', 4453),
 ('bo', 4323),
 ('bi', 4272),
 ('nr', 4198),
 ('be', 4174),
 ('ex', 4109),
 ('ab', 3976),
 ('sy', 3889),
 ('bu', 3807),
 ('ps', 3796),
 ('dl', 3673),
 ('iw', 3667),
 ('cl', 3382),
 ('ov', 3341),
 ('pt', 3275),
 ('mu', 3199),
 ('ks', 3194),
 ('av', 3190),
 ('aw', 3080),
 ('au', 3026),
 ('ip', 2988),
 ('ef', 2940),
 ('fr', 2880),
 ('lt', 2874),
 ('gs', 2841),
 ('px', 2756),
 ('lp', 2637),
 ('cu', 2622),
 ('ey', 2583),
 ('ls', 2548),
 ('cs', 2535),
 ('go', 2528),
 ('eu', 2494),
 ('by', 2454),
 ('gh', 2404),
 ('mp', 2393),
 ('dr', 2288),
 ('kr', 2283),
 ('ty', 2281),
 ('ry', 2274),
 ('oy', 2253),
 ('af', 2230),
 ('ak', 2225),
 ('mr', 2123),
 ('qu', 2076),
 ('nv', 2039),
 ('ds', 1953),
 ('br', 1912),
 ('ik', 1854),
 ('bl', 1760),
 ('ft', 1758),
 ('du', 1689),
 ('ju', 1682),
 ('hw', 1668),
 ('ko', 1623),
 ('jo', 1610),
 ('ny', 1585),
 ('kn', 1567),
 ('iu', 1537),
 ('uy', 1456),
 ('mt', 1451),
 ('sw', 1393),
 ('gu', 1352),
 ('lr', 1347),
 ('ax', 1298),
 ('nw', 1208),
 ('ms', 1147),
 ('gy', 1117),
 ('eo', 1116),
 ('hn', 1063),
 ('py', 1052),
 ('aj', 1045),
 ('fl', 1002),
 ('hp', 985),
 ('tw', 965),
 ('az', 940),
 ('ln', 896),
 ('rv', 827),
 ('fu', 807),
 ('gt', 768),
 ('bm', 699),
 ('kl', 687),
 ('hu', 684),
 ('my', 683),
 ('cx', 675),
 ('dt', 663),
 ('ej', 622),
 ('ao', 614),
 ('iz', 609),
 ('cm', 585),
 ('gp', 585),
 ('hr', 582),
 ('cy', 566),
 ('ez', 547),
 ('tx', 545),
 ('gl', 524),
 ('fn', 498),
 ('rw', 491),
 ('ix', 490),
 ('dy', 479),
 ('sv', 443),
 ('cd', 442),
 ('lm', 440),
 ('eq', 430),
 ('dg', 420),
 ('bt', 389),
 ('bs', 384),
 ('iy', 378),
 ('oz', 359),
 ('dp', 352),
 ('dm', 341),
 ('ij', 341),
 ('bn', 336),
 ('fs', 336),
 ('bc', 328),
 ('dv', 325),
 ('hy', 287),
 ('ox', 260),
 ('fy', 254),
 ('mn', 252),
 ('km', 251),
 ('df', 248),
 ('cp', 244),
 ('nz', 225),
 ('bd', 218),
 ('aq', 217),
 ('dw', 215),
 ('uz', 210),
 ('ku', 207),
 ('hl', 199),
 ('jn', 195),
 ('ky', 191),
 ('gm', 183),
 ('hm', 179),
 ('lw', 178),
 ('np', 177),
 ('cf', 176),
 ('kw', 176),
 ('dh', 165),
 ('kt', 164),
 ('cv', 153),
 ('wy', 150),
 ('bp', 142),
 ('tv', 140),
 ('cq', 139),
 ('vy', 139),
 ('sx', 131),
 ('lv', 125),
 ('qs', 118),
 ('pv', 112),
 ('dx', 100),
 ('tz', 100),
 ('hk', 99),
 ('js', 98),
 ('bv', 95),
 ('fp', 95),
 ('cg', 93),
 ('jt', 93),
 ('bg', 91),
 ('lx', 89),
 ('dk', 87),
 ('gv', 87),
 ('fm', 86),
 ('nx', 85),
 ('fv', 83),
 ('mx', 83),
 ('dj', 82),
 ('kp', 81),
 ('mw', 79),
 ('bh', 77),
 ('gz', 77),
 ('iq', 75),
 ('fh', 72),
 ('uv', 71),
 ('rx', 70),
 ('fw', 69),
 ('pw', 68),
 ('qt', 65),
 ('bj', 62),
 ('lz', 59),
 ('qr', 57),
 ('bf', 56),
 ('bk', 56),
 ('fg', 56),
 ('jr', 55),
 ('gw', 52),
 ('fk', 50),
 ('hx', 50),
 ('rz', 50),
 ('jp', 48),
 ('xy', 48),
 ('yz', 44),
 ('bx', 43),
 ('dq', 39),
 ('lq', 39),
 ('fx', 36),
 ('cw', 35),
 ('oq', 34),
 ('hv', 33),
 ('jm', 33),
 ('jx', 31),
 ('mz', 31),
 ('sz', 30),
 ('bw', 29),
 ('hz', 29),
 ('gx', 27),
 ('dz', 26),
 ('jy', 25),
 ('mv', 24),
 ('nq', 24),
 ('ux', 22),
 ('gj', 21),
 ('hj', 21),
 ('bz', 18),
 ('hq', 18),
 ('kz', 18),
 ('vw', 18),
 ('jv', 17),
 ('cz', 16),
 ('jw', 16),
 ('cj', 15),
 ('uw', 15),
 ('gk', 14),
 ('jl', 13),
 ('fj', 11),
 ('qy', 11),
 ('vx', 11),
 ('kv', 8),
 ('kx', 8),
 ('pz', 8),
 ('qw', 7),
 ('fq', 5),
 ('pq', 5),
 ('bq', 4),
 ('mq', 4),
 ('vz', 4),
 ('jk', 3),
 ('jz', 3),
 ('fz', 2),
 ('qz', 2),
 ('wz', 2),
 ('gq', 1),
 ('jq', 1),
 ('qx', 1),
 ('wx', 1),
 ('xz', 1),
 ('kq', 0),
 ('qv', 0)]
alpha_List = [chr(i) for i in range(ord('a'),ord('z')+1)]
alpha_List.index('a')

weights = [x[1] for x in f_count]
#                                        standardized similarity matrix with inverse relation
sum_counting = sum(weights)
edges = []
for x in f_count:
    edges.append((alpha_List.index(x[0][0]),alpha_List.index(x[0][1])))
edges = [(i, j, 1- w/sum_counting) for (i, j),w in zip(edges, weights)]


# edges = []
# for x in f_count:
#     edges.append((alpha_List.index(x[0][0]),alpha_List.index(x[0][1])))
# edges = [(i, j, w) for (i, j),w in zip(edges, weights)]

#initialize afficinity matrix
affinity = np.zeros((26,26))
#updating value in afficinity using edges
for edge in edges:
    i,j,w = edge
    affinity[i][j] = w
    affinity[j][i] = w 


In [78]:
# def init_affinity():
#from source_code.spectral_esc import SpectralEqualSizeClustering   
for i in range(1):
    clustering = SpectralClustering(n_clusters=8,n_neighbors = 3,affinity='precomputed').fit(affinity)
    labels = clustering.labels_
    print(labels)
for i in range(8):
    print(np.where(labels == i)[0])

[0 2 0 4 1 0 6 4 3 2 4 6 0 2 7 2 2 4 2 5 0 0 0 0 4 0]
[ 0  2  5 12 20 21 22 23 25]
[4]
[ 1  9 13 15 16 18]
[8]
[ 3  7 10 17 24]
[19]
[ 6 11]
[14]
